spring.application.name=security-console

spring.datasource.url=jdbc:postgresql://localhost:5432/bit34
spring.datasource.username=bit34
spring.datasource.password=bit34pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=8080

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=security-console-group
spring.kafka.consumer.auto-offset-reset=earliest